name: arb_utils
description: A set of tools to work with .arb files (the preferred Dart way of dealing with i18n/l10n/translations)
version: 0.8.3
repository: https://github.com/Rodsevich/arb_utils
homepage: https://gitlab.com/Rodsevich/arb_utils

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.4.2
  collection: ^1.19.1
  intl: ^0.20.2
  intl_utils: ^2.8.10
  shared_preferences: ^2.5.3
  dcli: ^7.0.5
  dart_console: ^4.1.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  win32: ^5.14.0

executables:
  arb_utils:
